### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by lvndry** [ckaznocha/ide-go#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: "Manjaro Linux"
**Thrown From**: [ide-go](https://github.com/ckaznocha/ide-go) package 0.5.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /home/lvndry/.atom/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -1:32.8.0 core:move-right (input.hidden-input)
     -1:31.9.0 editor:newline (input.hidden-input)
     -1:30.4.0 core:backspace (input.hidden-input)
     -1:29.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:27.7.0 core:move-down (input.hidden-input)
     -1:27.4.0 autocomplete-plus:confirm (input.hidden-input)
     -1:25 intentions:highlight (input.hidden-input)
     -1:24.9.0 core:save (input.hidden-input)
     -0:21.5.0 core:move-right (input.hidden-input)
     -0:21.3.0 intentions:highlight (input.hidden-input)
  3x -0:21.2.0 editor:select-to-beginning-of-word (input.hidden-input)
  7x -0:18.8.0 core:backspace (input.hidden-input)
     -0:12.9.0 intentions:highlight (input.hidden-input)
     -0:12.9.0 core:save (input.hidden-input)
     -0:11.1.0 intentions:highlight (input.hidden-input)
     -0:11.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.1 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
cdn-libs 0.1.3 
clipboard-plus 0.5.1 
color-picker 2.2.5 
css-snippets 1.1.0 
emmet 2.4.3 
etheratom 3.2.0 
file-icons 2.1.16 
go-imports 0.1.1 
go-plus 5.7.2 
hey-pane 1.1.0 
highlight-selected 0.13.1 
ide-go 0.5.0 
intentions 1.1.5 
java-generator 2.2.3 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-ethereum 0.3.9 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-ui-default 1.6.10 
material-ui 1.0.10 
minimap 4.29.7 
oceanic-next 1.0.0 
pigments 0.40.2 
project-manager 3.3.5 
react 0.17.0 
```

**Comment by ckaznocha** [comment]
Even though this is the older issue there is more conversation at #25, closing this one as a dupe just to consolidate.
