### ISSUE TITLE
Uncaught TypeError: this.getLanguageName is not a function

### ISSUE THREAD

**Issue by jojomi** [ckaznocha/ide-go#17]
Steps to reproduce:

1. just started Atom

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [ide-go](https://github.com/ckaznocha/ide-go) package 0.6.0

### Stack Trace

Uncaught TypeError: this.getLanguageName is not a function

```
At /Users/johannes/.atom/packages/ide-go/lib/ide-go.js:146

TypeError: this.getLanguageName is not a function
    at ChildProcess.onExit (/packages/ide-go/lib/ide-go.js:146:25)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
aligner-php 1.2.0 
appcelerator-titanium 1.0.3 
asciidoc-preview 2.10.3 
atom-beautify 0.30.9 
atom-ide-ui 0.7.2 
atom-sync-cygwin 0.9.19 
atom-typescript 12.1.1 
autocomplete-php 0.3.7 
blame 1.0.1 
build 0.70.0 
busy-signal 1.4.3 
color-picker 2.2.5 
colors 1.0.1 
docblockr 0.13.6 
emmet 2.4.3 
git-blame 1.5.0 
git-line 0.6.0 
git-plus 7.10.0 
github-2016-syntax 1.2.0 
go-debug 1.6.0 
go-plus 5.8.1 
go-signature-statusbar 1.2.3 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-go 0.6.0 
ide-php 0.7.4 
intentions 1.1.5 
jscs-fixer 1.3.0 
language-asciidoc 1.11.0 
language-latex 1.1.1 
latex-completions 0.3.3 
linter 2.2.0 
linter-jscs 4.1.3 
linter-phpcs 1.6.8 
linter-ui-default 1.6.10 
mac-github-syntax 1.3.9 
minimap 4.29.7 
minimap-autohider 1.5.3 
minimap-bookmarks 0.4.2 
minimap-highlight-selected 4.6.1 
nord-atom-syntax 0.9.1 
pandoc 0.2.2 
phantom-ui 1.0.0 
project-manager 3.3.5 
semanticolor 3.5.5 
tablr 1.8.3 
tablr-json 0.1.0 
tabs-to-spaces 1.0.3 
to-do 0.2.0 
toggler 0.3.1 
```

**Comment by yefremov** [comment]
Same issues, just installed fresh `atom`, `atom-ide-ui` and `ide-go`

**Comment by MovieStoreGuy** [comment]
This should not have been closed without a good explanation.
