### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by thedrow** [ckaznocha/ide-go#25]
I don't know how to reproduce this. It just happens...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 17.10
**Thrown From**: [ide-go](https://github.com/ckaznocha/ide-go) package 0.7.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /home/omer/.atom/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### Commands

```
     -8:07.9.0 core:cut (input.hidden-input)
     -8:07.2.0 intentions:highlight (input.hidden-input)
     -8:07.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.11.1 
autocomplete-python 1.10.5 
build 0.70.0 
build-cmake 0.11.0 
build-dockerfile 1.0.1 
build-make 0.13.0 
build-python 0.9.3 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.19 
go-debug 1.6.1 
go-plus 5.8.3 
ide-cpp 0.0.3 
ide-go 0.7.0 
ide-python 0.9.2 
ide-ruby 0.1.10 
ide-rust 0.16.0 
intentions 1.1.5 
language-cmake 1.1.0 
language-cython 0.3.0 
language-docker 1.1.8 
language-ini 1.19.0 
language-nginx 0.8.0 
language-pgsql 0.2.3 
language-restructuredtext 1.1.2 
language-rust 0.4.12 
language-systemd 0.1.1 
language-terraform 0.8.1 
language-thrift 1.0.2 
linter 2.2.0 
linter-docker 0.3.2 
linter-pylama 0.9.5 
linter-terraform-semantics 0.2.0 
linter-terraform-syntax 1.2.2 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-autohide 0.10.1 
minimap-linter 2.1.3 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.1.5 
python-isort 0.0.7 
python-mrigor 2.1.3 
python-tools 0.6.9 
rst-preview 1.3.1 
terminal-plus 0.14.5 
terraform-fmt 0.3.0 
```

**Comment by Cxarli** [comment]
Same here. Seems to happen when hovering over text

**Comment by pwaller** [comment]
It's happening for me for virtually every keypress and is making it unusable. I think it may be caused by the fact that the code I'm editing is currently malformed while in the middle of a big refactor, and I guess the langserver is crashing or malfunctioning. But I can't easily see how to inspect what's going on with the langserver.

**Comment by ckaznocha** [comment]
It's hard to tell what caused go-langserver to crash without the stack trace from go-langserver itself. Possibly related to [this issue](https://github.com/sourcegraph/go-langserver/issues/300). I haven't yet seen this myself, does anyone know if this is this still an issue after updating to a newer version of go-langserver?

**Comment by mdouchement** [comment]
Got the same issue when I'm typing the following comment `//nolint`

<details>
<summary>Atom stacktrace</summary>

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [ide-go](https://github.com/ckaznocha/ide-go) package 0.12.3


### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/mdouchem/.atom/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
file-icons 2.1.24 
hyperclick 0.0.0 
ide-go 0.12.3 
language-docker 1.1.8 
monokai 0.24.0 
pretty-json 2.0.3 
```

</details>

</br>


- Golang: `go version go1.11 darwin/amd64`
- go-langserver `7df19dc017efdd578d75c81016e0b512f3914cc1` (latest master)


The logs of `go-langserver -logfile /tmp/go-langserver.log -diagnostics` command:
```
langserver-go: reading on stdin, writing on stdout
Passing an initialize rootPath URI ("file:///Users/mdouchement/workspaces/golang/src/github.com/mdouchement/vdf/") is deprecated. Use rootUri instead.
```
This path exists on my computer.
