### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by ehames** [ckaznocha/ide-go#34]
[Enter steps to reproduce:]

1. Rename variable

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.11.6
**Thrown From**: [ide-go](https://github.com/ckaznocha/ide-go) package 0.12.3

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/edgardo/.atom/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-go/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -0:26 editor:consolidate-selections (input.hidden-input)
     -0:26 core:cancel (input.hidden-input)
     -0:25.7.0 editor:consolidate-selections (input.hidden-input)
     -0:25.7.0 core:cancel (input.hidden-input)
     -0:25.5.0 editor:consolidate-selections (input.hidden-input)
     -0:25.5.0 core:cancel (input.hidden-input)
     -0:25.2.0 editor:consolidate-selections (input.hidden-input)
     -0:25.2.0 core:cancel (input.hidden-input)
  2x -0:19 core:paste (a.stack-toggle)
     -0:16.7.0 core:save (input.hidden-input)
     -0:08.9.0 editor:consolidate-selections (input.hidden-input)
     -0:08.9.0 core:cancel (input.hidden-input)
     -0:07.3.0 core:paste (input.hidden-input)
     -0:05.8.0 editor:consolidate-selections (input.hidden-input)
     -0:05.8.0 core:cancel (input.hidden-input)
     -0:04.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
file-icons 2.1.24 
gherkin-autocomplete 2.0.0 
go-debug 1.6.2 
go-find-references 1.2.3 
go-imports 0.1.1 
go-outline 0.6.7 
go-plus 5.8.6 
go-rename 0.3.0 
go-signature-statusbar 1.2.3 
Hydrogen 2.5.1 
ide-go 0.12.3 
json-to-go-struct 0.0.5 
language-docker 1.1.8 
language-gherkin 1.0.4 
language-plantuml 0.2.0 
rest-client 1.3.1 
todo-show 2.3.2 
```

**Comment by kdomanski** [comment]
Same issue here.
**Atom**: `1.30.0`
**ide-go**: `0.12.3`
**OS**: Ubuntu 16.04

**Comment by zac-garby** [comment]
Same,
Atom: 1.30.0
ide-go: 0.12.3
OS: macOS 10.14 Beta

For me, I get the error when the package would attempt to autocomplete.

**Comment by kdomanski** [comment]
Rebuilding and restarting latest `github.com/sourcegraph/go-langserver` and `github.com/nsf/gocode` solved the issue for me.

**Comment by ckaznocha** [comment]
Glad you found a solution. Closing this one but I’ll keep #25 open because I think this error will pop up again for other scenarios.
