### ISSUE TITLE
Error while opening go file

### ISSUE THREAD

**Issue by kifirkin** [ckaznocha/ide-go#5]
```
C:\Users\alex\.atom\packages\ide-go\node_modules\vscode-jsonrpc\lib\messages.js:46 Uncaught (in promise) Error: invalid root URI "file://C:\\homework\\go\\src\\git\\group\\repo\\": must be file:/// URI
    at new ResponseError (C:\Users\alex\.atom\packages\ide-go\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
    at handleResponse (C:\Users\alex\.atom\packages\ide-go\node_modules\vscode-jsonrpc\lib\main.js:421:48)
    at processMessageQueue (C:\Users\alex\.atom\packages\ide-go\node_modules\vscode-jsonrpc\lib\main.js:249:17)
    at Immediate.<anonymous> (C:\Users\alex\.atom\packages\ide-go\node_modules\vscode-jsonrpc\lib\main.js:233:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

There is a conflict with `go-plus` package

**Comment by ckaznocha** [comment]
The latest release has some better error handling. Could please update and post back here if your still having this issue?

**Comment by kifirkin** [comment]
@ckaznocha 
after a year... 😅 
I've just get back to Atom. this error has gone, thanks!

**Comment by ckaznocha** [comment]
Great! Thanks for revising this!
