### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by afoninsky** [ckaznocha/ide-go#7]
It happens often then i'm editing golang file

**Atom**: 1.21.0-beta2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-go](https://github.com/ckaznocha/ide-go) package 0.4.0

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/drago/.atom/packages/ide-go/node_modules/vscode-jsonrpc/lib/main.js:606

Error: Connection is closed.
    at /packages/ide-go/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (/packages/ide-go/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (/packages/ide-go/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (/packages/ide-go/node_modules/atom-languageclient/build/lib/languageclient.js:244:15)
    at LanguageClientConnection.didChangeTextDocument (/packages/ide-go/node_modules/atom-languageclient/build/lib/languageclient.js:133:10)
    at TextEditorSyncAdapter.sendFullChanges (/packages/ide-go/node_modules/atom-languageclient/build/lib/adapters/document-sync-adapter.js:183:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:823:24)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:781:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:780:47)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:763:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1002:22)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:956:20)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2621:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1631:28)
```

### Commands

```
     -0:13.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:08.1.0 core:save (input.hidden-input)
     -0:05.9.0 core:copy (input.hidden-input)
     -0:04.4.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
busy-signal 1.4.3 
docblockr 0.11.0 
editorconfig 2.2.2 
file-icons 2.1.12 
git-plus 7.9.3 
git-time-machine 1.5.9 
go-plus 5.5.5 
go-signature-statusbar 1.2.3 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-go 0.4.0 
ide-json 0.1.0 
ide-typescript 0.6.1 
ide-yaml 0.1.6 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.3.2 
linter-golinter 1.2.2 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-ui-default 1.6.10 
sync-settings 0.8.3 
```

**Comment by aprakash-sovrn** [comment]
This one would be great to get looked at soon!

**Comment by rajatjindal** [comment]
anyone looking at it yet?

**Comment by dylanmacdonald** [comment]
This is still occuring...

**Comment by ckaznocha** [comment]
Sorry for the delay on this one. I'm not sure why this is happening or how to recreate it. My best guess is something is causing go-langserver to crash. I've added better error handling so now we should at least see what is causing the connection to close and get it resolved. At the very least it should be a better experience when the connection does close. I'll close this for now, if it turns out its not something that should be fixed in go-langserver I'll re-open it. Please update your plugin once its release and post back here with any new error details.
